firstspeech=["ABOUT to undertake the arduous duties that I have been appointed to perform by the choice of a free people",
             "I avail myself of this customary and solemn occasion to express the gratitude which their confidence inspires and to acknowledge the accountability which my situation enjoins",
             "While the magnitude of their interests convinces me that no thanks can be adequate to the honor they have conferred",
             "it admonishes me that the best return I can make is the zealous dedication of my humble abilities to their service and their good",
             "As the instrument of the Federal Constitution it will devolve on me for a stated period to execute the laws of the United States",
             "to superintend their foreign and their confederate relations to manage their revenue to command their forces and by communications to the Legislature",
             "to watch over and to promote their interests generally. And the principles of action by which I shall endeavor to accomplish this circle of duties it is now proper for me briefly to explain",
             "In administering the laws of Congress I shall keep steadily in view the limitations as well as the extent of the Executive power", 
             "trusting thereby to discharge the functions of my office without transcending its authority",
             "With foreign nations it will be my study to preserve peace and to cultivate friendship on fair and honorable terms",
             "and in the adjustment of any differences that may exist or arise to exhibit the forbearance becoming a powerful nation rather than the sensibility belonging to a gallant people",
             "In such measures as I may be called on to pursue in regard to the rights of the separate States I hope to be animated by a proper respect for those sovereign members of our Union",
             "taking care not to confound the powers they have reserved to themselves with those they have granted to the Confederacy",
             "The management of the public revenue - that searching operation in all governments - is among the most delicate and important trusts in ours, and it will",
             "of course  demand no inconsiderable share of my official solicitude. Under every aspect in which it can be considered it would appear that advantage must result from the observance of a strict and faithful economy",
             "This I shall aim at the more anxiously both because it will facilitate the extinguishment of the national debt the unnecessary duration of which is incompatible with real independence",
             "and because it will counteract that tendency to public and private profligacy which a profuse expenditure of money by the Government is but too apt to engender",
             "Powerful auxiliaries to the attainment of this desirable end are to be found in the regulations provided by the wisdom of Congress for the specific appropriation of public money and the prompt accountability of public officers",
             "With regard to a proper selection of the subjects of impost with a view to revenue it would seem to me that the spirit of equity caution",
             "and compromise in which the Constitution was formed requires that the great interests of agriculture",
             "commerce and manufactures should be equally favored and that perhaps the only exception to this rule should consist in the peculiar encouragement of any products of either of them that may be found essential to our national independence",
             "Internal improvement and the diffusion of knowledge so far as they can be promoted by the constitutional acts of the Federal Government are of high importance",
             "Considering standing armies as dangerous to free governments in time of peace I shall not seek to enlarge our present establishment nor disregard that salutary lesson of political experience which teaches that the military should be held subordinate to the civil power The gradual increase of our Navy whose flag has displayed in distant climes our skill in navigation and our fame in arms ; the preservation of our forts, arsenals, and dockyards, and the introduction of progressive improvements in the discipline and science of both branches of our military service are so plainly prescribed by prudence that I should be excused for omitting their mention sooner than for enlarging on their importance  But the bulwark of our defense is the national militia , which in the present state of our intelligence and population must render us invincible As long as our Government is administered for the good of the people and is regulated by their will as long as it secures to us the rights of person and of property liberty of conscience and of the press it will be worth defending and so long as it is worth defending a patriotic militia will cover it with an impenetrable aegis Partial injuries and occasional mortifications we may be subjected to but a million of armed freemen possessed of the means of war can never be conquered by a foreign foe To any just system therefore calculated to strengthen this natural safeguard of the country I shall cheerfully lend all the aid in my power",
             "It will be my sincere and constant desire to observe toward the Indian tribes within our limits a just and liberal policy and to give that humane and considerate attention to their rights and their wants which is consistent with the habits of our Government and the feelings of our people",
             "The recent demonstration of public sentiment inscribes on the list of Executive duties in characters too legible to be overlooked the task of reform which will require particularly the correction of those abuses that have brought the patronage of the Federal Government into conflict with the freedom of elections and the counteraction of those causes which have disturbed the rightful course of appointment and have placed or continued power in unfaithful or incompetent hands",
             "In the performance of a task thus generally delineated I shall endeavor to select men whose diligence and talents will insure in their respective stations able and faithful cooperation depending for the advancement of the public service more on the integrity and zeal of the public officers than on their numbers",
             "A diffidence perhaps too just in my own qualifications will teach me to look with reverence to the examples of public virtue left by my illustrious predecessors and with veneration to the lights that flow from the mind that founded and the mind that reformed our system. The same diffidence induces me to hope for instruction and aid from the coordinate branches of the Government and for the indulgence and support of my fellow-citizens generally . And a firm reliance on the goodness of that Power whose providence mercifully protected our national infancy and has since upheld our liberties in various vicissitudes encourages me to offer up my ardent supplications that He will continue to make our beloved country the object of His divine care and gracious benediction"]
secondspeech=["THE will of the American people expressed through their unsolicited suffrages calls me before you to pass through the solemnities preparatory to taking upon myself the duties of President of the United States for another term For their approbation of my public conduct through a period which has not been without its difficulties and for this renewed expression of their confidence in my good intentions I am at a loss for terms adequate to the expression of my gratitude It shall be displayed to the extent of my humble abilities in continued efforts so to administer the Government as to preserve their liberty and promote their happiness",
             "So many events have occurred within the last four years which have necessarily called forth - sometimes under circumstances the most delicate and painful - my views of the principles and policy which ought to be pursued by the General Government that I need on this occasion but allude to a few leading considerations connected with some of them",
             "The foreign policy adopted by our Government soon after the formation of our present Constitution and very generally pursued by successive Administrations has been crowned with almost complete success and has elevated our character among the nations of the earth To do justice to all and to submit to wrong from none has been during my Administration its governing maxim and so happy have been its results that we are not only at peace with all the world but have few causes of controversy and those of minor importance remaining unadjusted",
             "In the domestic policy of this Government there are two objects which especially deserve the attention of the people and their representatives and which have been and will continue to be the subjects of my increasing solicitude They are the preservation of the rights of the several States and the integrity of the Union",
             "These great objects are necessarily connected and can only be attained by an enlightened exercise of the powers of each within its appropriate sphere in conformity with the public will constitutionally expressed To this end it becomes the duty of all to yield a ready and patriotic submission to the laws constitutionally enacted and thereby promote and strengthen a proper confidence in those institutions of the several States and of the United States which the people themselves have ordained for their own government",
             "My experience in public concerns and the observation of a life somewhat advanced confirm the opinions long since imbibed by me that the destruction of our State governments or the annihilation of their control over the local concerns of the people would lead directly to revolution and anarchy and finally to despotism and military domination. In proportion therefore as the General Government encroaches upon the rights of the States in the same proportion does it impair its own power and detract from its ability to fulfill the purposes of its creation Solemnly impressed with these considerations my countrymen will ever find me ready to exercise my constitutional powers in arresting measures which may directly or indirectly encroach upon the rights of the States or tend to consolidate all political power in the General Government But of equal and indeed of incalculable importance is the union of these States and the sacred duty of all to contribute to its preservation by a liberal support of the General Government in the exercise of its just powers You have been wisely admonished to accustom yourselves to think and speak of the Union as of the palladium of your political safety and prosperity watching for its preservation with jealous anxiety discountenancing whatever may suggest even a suspicion that it can in any event be abandoned and indignantly frowning upon the first dawning of any attempt to alienate any portion of our country from the rest or to enfeeble the sacred ties which now link together the various parts Without union our independence and liberty would never have been achieved ; without union they never can be maintained Divided into twenty-four or even a smaller number of separate communities we shall see our internal trade burdened with numberless restraints and exactions ; communication between distant points and sections obstructed or cut off ; our sons made soldiers to deluge with blood the fields they now till in peace ; the mass of our people borne down and impoverished by taxes to support armies and navies and military leaders at the head of their victorious legions becoming our lawgivers and judges The loss of liberty of all good government of peace plenty and happiness must inevitably follow a dissolution of the Union In supporting it therefore we support all that is dear to the freeman and the philanthropist",
             "The time at which I stand before you is full of interest. The eyes of all nations are fixed on our Republic The event of the existing crisis will be decisive in the opinion of mankind of the practicability of our federal system of government Great is the stake placed in our hands ; great is the responsibility which must rest upon the people of the United States Let us realize the importance of the attitude in which we stand before the world Let us exercise forbearance and firmness Let us extricate our country from the dangers which surround it and learn wisdom from the lessons they inculcate",
             "Deeply impressed with the truth of these observations and under the obligation of that solemn oath which I am about to take I shall continue to exert all my faculties to maintain the just powers of the Constitution and to transmit unimpaired to posterity the blessings of our Federal Union At the same time it will be my aim to inculcate by my official acts the necessity of exercising by the General Government those powers only that are clearly delegated ; to encourage simplicity and economy in the expenditures of the Government ; to raise no more money from the people than may be requisite for these objects and in a manner that will best promote the interests of all classes of the community and of all portions of the Union. Constantly bearing in mind that in entering into society individuals must give up a share of liberty to preserve the rest it will be my desire so to discharge my duties as to foster with our brethren in all parts of the country a spirit of liberal concession and compromise and by reconciling our fellow-citizens to those partial sacrifices which they must unavoidably make for the preservation of a greater good to recommend our invaluable Government and Union to the confidence and affections of the American people",
             "Finally it is my most fervent prayer to that Almighty Being before whom I now stand and who has kept us in His hands from the infancy of our Republic to the present day that He will so overrule all my intentions and actions and inspire the hearts of my fellow-citizens that we may be preserved from dangers of all kinds and continue forever a united and happy people"]
d=dict()
for i in range(0,len(firstspeech)):
    k=firstspeech[i]
    for c in k.split():
        if c not in d:
            d[c]=1
        else:
            d[c]=d[c]+1
d2=dict()
for j in range(0,len(secondspeech)):
    q=secondspeech[j]
    for v in q.split():
        if v not in d2:
            d2[v]=1
        else:
            d2[v]=d2[v]+1
for a in d:
    if d[a]>14:
        print "firstspeech",a
        print d[a]
for w in d2:    
    if d2[w]>12:
        print "secondspeech",w
        print d[w]
        